### PR TITLE
UI component refactor and testing

### PR DESCRIPTION
**Pull request by mbland**
The refactoring is relatively minor, but the testing is pretty extensive. Open to the idea of porting these components and tests to 18F/lunr-server or another npm first rather than checking them directly into the gem.

Confirmed the tests pass with PhantomJS 2.1.1, Chrome 49.0.2623.75, Safari 9.0.3, and Firefox 45.0. Also confirmed it continues to work with [18F/guides-template](https://github.com/18F/guides-template/) and [presidential-innovation-fellows/apps-gov](https://github.com/presidential-innovation-fellows/apps-gov).

cc: @catherinedevlin @jbarnicle @afeld @stroupaloop

### CODE REVIEW

**Comment by mbland** [comment]
Closes #26.

**Comment by mbland** [comment]
Also germane to #27.

**Comment by mbland** [comment]
Ping... Any preference as to how to move forward on this?

**Comment by jbarnicle** [comment]
@mbland I'll try and review this PR over the weekend.  As far as migrating JS components to lunr-server, I'm not sure how valuable that would be.  The UI approaches across sites can vary greatly and I would think most likely be overridden on the client side in most cases.  The design for the aggregated results varies greatly from the existing implementation.

**Pull request closed without merging**
